export const FETCH_MOVIES_LIST = 'FETCH_MOVIES_LIST'
export const FETCH_MOVIES_LIST_SUCCESS = 'FETCH_MOVIES_LIST_SUCCESS'
export const FETCH_MOVIES_LIST_FAILURE = 'FETCH_MOVIES_LIST_FAILURE'

export const FETCH_CHAR_NAMES = 'FETCH_CHAR_NAMES'
export const FETCH_CHAR_NAMES_SUCCESS = 'FETCH_CHAR_NAMES_SUCCESS'
export const FETCH_CHAR_NAMES_FAILURE = 'FETCH_CHAR_NAMES_FAILURE'

export const FETCH_PLANETS_DETAILS = 'FETCH_PLANETS_DETAILS'
export const FETCH_PLANETS_DETAILS_SUCCESS = 'FETCH_PLANETS_DETAILS_SUCCESS'
export const FETCH_PLANETS_DETAILS_FAILURE = 'FETCH_PLANETS_DETAILS_FAILURE'

export const FETCH_STARS_SHIPS_DETAILS = 'FETCH_STARS_SHIPS_DETAILS'
export const FETCH_STARS_SHIPS_DETAILS_SUCCESS = 'FETCH_STARS_SHIPS_DETAILS_SUCCESS'
export const FETCH_STARS_SHIPS_DETAILS_FAILURE = 'FETCH_STARS_SHIPS_DETAILS_FAILURE'


export const STORE_CURRENT_SLIDE_INDEX = 'STORE_CURRENT_SLIDE_INDEX'